name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.3'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up MySQL
      uses: clewolff/mysql-action@v1
      with:
        mysql-version: '5.7'
        database: 'home_kitchen_db'
        user: 'root'
        password: 'sss27'

    - name: Run tests
      run: |
        pytest
