name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install MySQL
      run: |
        sudo apt-get update
        sudo apt-get install -y mysql-server
        sudo service mysql start
        sudo mysql -e "CREATE DATABASE home_kitchen_db;"
        # Create a dedicated user with limited privileges
        sudo mysql -e "CREATE USER 'db_user'@'localhost' IDENTIFIED BY 'strong_password';"
        sudo mysql -e "GRANT ALL PRIVILEGES ON home_kitchen_db.* TO 'db_user'@'localhost';"
        sudo mysql -e "FLUSH PRIVILEGES;"

    - name: Run tests
      env:
        DB_NAME: home_kitchen_db
        DB_USER: db_user
        DB_PASSWORD: strong_password
      run: |
        pytest