name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    # fic
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up MySQL
        uses: mirromutth/mysql-action@v1
        with:
          mysql-version: '8.0'
          mysql-root-password: ${{ secrets.MYSQL_ROOT_PASSWORD }}

      - name: Run MySQL command
        run: |
          mysql -u root -p${{ secrets.MYSQL_ROOT_PASSWORD }} -e "SHOW DATABASES;"          